'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let doctors=[],chosen=null,product=0,draft={},lastOrder=null,cufflink=false,pendingGift=false;
const products=[['İmza Gömlek','3.500 TL'],['Manşet Koleksiyonu','4.500 TL'],['Çizgili İmza','3.750 TL']];
const prices=[3500,4500,3750],cufflinkPrice=1250;
const money=n=>n.toLocaleString('tr-TR')+' TL';
const hasCufflink=()=>product===1&&cufflink;
const total=()=>prices[product]+(hasCufflink()?cufflinkPrice:0);
const norm=s=>s.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');
const dialog=$('#flow');
function show(html,premium=false){dialog.classList.toggle('accessory-dialog',premium);dialog.removeAttribute('aria-labelledby');$('#flowbody').innerHTML=html;if(!dialog.open)dialog.showModal();}
dialog.addEventListener('close',()=>dialog.classList.remove('accessory-dialog'));
$('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function find(){let q=norm($('#doctor').value.trim());let matches=doctors.filter(d=>norm(d.name+' '+d.branch+' '+d.institution).includes(q)).slice(0,12);$('#results').hidden=false;$('#doctor').setAttribute('aria-expanded','true');$('#results').innerHTML=matches.length?matches.map(d=>`<button data-doctor="${d.id}">${esc(d.title+' '+d.name)}<span>${esc(d.branch)}</span><span>${esc(d.institution)}</span></button>`).join(''):'<p>Bu isim listede bulunamadı. Doktor adını veya branşını farklı yazarak deneyin.</p>';$('#results').querySelectorAll('button').forEach(b=>b.onclick=()=>selectDoctor(b.dataset.doctor));}
function selectDoctor(id){chosen=doctors.find(d=>d.id===id);if(!chosen)throw Error('Doktor bulunamadı');$('#doctor').value=chosen.name;$('#selected').textContent=chosen.name+' seçildi. Şimdi hediyenizi seçebilirsiniz.';$('#results').hidden=true;$('#doctor').setAttribute('aria-expanded','false');if(pendingGift){pendingGift=false;details();}else $('#koleksiyon').scrollIntoView({behavior:'smooth'});}
$('#doctor').addEventListener('input',()=>{chosen=null;$('#selected').textContent='';find();});$('#doctor').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();find();$('#results button')?.focus();}if(e.key==='Escape'){$('#results').hidden=true;$('#doctor').setAttribute('aria-expanded','false');}});$('#search').onclick=find;
document.addEventListener('click',e=>{if(!e.target.closest('.finder')){$('#results').hidden=true;$('#doctor').setAttribute('aria-expanded','false');}});
function continueGift(){
 if(!chosen){
  pendingGift=true;dialog.close();
  $('#doctor').scrollIntoView({block:'center',behavior:'smooth'});$('#doctor').focus({preventScroll:true});
  find();$('#selected').textContent=products[product][0]+' seçildi. Devam etmek için doktorunuzu seçin.';return;
 }
 pendingGift=false;details();
}
document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{
 product=Number(b.dataset.product);pendingGift=false;
 if(product===1){chooseCufflinks();return;}
 cufflink=false;continueGift();
});
function chooseCufflinks(){
 show(`<div class="accessory-preview"><img src="assets/cufflinks.png" alt="Özel lacivert kutusunda gümüş tonlu Siyah Oval kol düğmesi çifti" width="1122" height="1402"><div class="accessory-preview-caption"><span>THE FINISHING TOUCH</span><strong>Küçük bir detay.<br>Eksiksiz bir hediye.</strong></div></div><div class="accessory-panel"><div class="eyebrow">FRENCH CUFF / 01</div><h2 id="accessory-title">Son dokunuş,<br><em>sizin seçiminiz.</em></h2><p id="accessory-description">Çift manşetin zarafetini bir çift kol düğmesiyle tamamlayın. Kendi kol düğmesini kullanacaksa yalnızca gömleği seçebilirsiniz.</p><fieldset class="premium-options"><legend>Hediyenizi nasıl hazırlayalım?</legend><label class="premium-choice"><input type="radio" name="accessory-first" value="oval" ${cufflink?'checked':''}><span><strong>Siyah Oval ile tamamla</strong><small>Gümüş tonlu · bir çift · özel kutusunda</small></span><b>+${money(cufflinkPrice)}</b></label><label class="premium-choice"><input type="radio" name="accessory-first" value="none" ${!cufflink?'checked':''}><span><strong>Yalnızca gömlek</strong><small>Kol düğmesi eklemeden devam et</small></span><b>+0 TL</b></label></fieldset><div class="accessory-receipt" aria-live="polite"><div><span>Manşet Koleksiyonu</span><span>${money(prices[1])}</span></div><div><span>Kol düğmesi</span><span id="accessory-extra">${cufflink?money(cufflinkPrice):'Eklenmedi'}</span></div><div class="accessory-grand"><span>Hediye toplamı</span><strong id="accessory-total">${money(total())}</strong></div></div><button class="primary accessory-continue" id="accessory-next">${chosen?'Hediye detaylarına geç':'Doktorunuzu seçin'} <span>→</span></button><p class="accessory-footnote">Kol düğmesi isteğe bağlıdır. Fiyatlar örnektir; satış henüz açık değildir.</p></div>`,true);
 dialog.setAttribute('aria-labelledby','accessory-title');
 document.querySelectorAll('input[name="accessory-first"]').forEach(input=>input.onchange=()=>{
  cufflink=input.value==='oval';$('#accessory-extra').textContent=cufflink?money(cufflinkPrice):'Eklenmedi';$('#accessory-total').textContent=money(total());
 });
 $('#accessory-next').onclick=continueGift;
}
function summary(){return `<div class="summary"><strong>${esc(products[product][0])} · ${products[product][1]}</strong><p>${esc(chosen.title+' '+chosen.name)}</p><p>${esc(chosen.branch)} · ${esc(chosen.institution)}</p><div id="orderPrice" aria-live="polite">${priceSummary()}</div></div>`;}
function priceSummary(){return `${product===1?`<p>${hasCufflink()?'Siyah Oval kol düğmesi (çift) · +'+money(cufflinkPrice):'Kol düğmesi eklenmedi'}</p>`:''}<p class="order-total"><span>Örnek toplam</span><strong>${money(total())}</strong></p>`;}
function accessoryOptions(){return product===1?`<fieldset class="cufflink-options"><legend>Manşetin son dokunuşu</legend><p>Çift manşet kol düğmesiyle kullanılır. Doktorunuzun kendi kol düğmesi varsa eklemeden devam edebilirsiniz.</p><label class="accessory-choice"><input type="radio" name="cufflink" value="none" ${!cufflink?'checked':''}><span>Kol düğmesi ekleme<small>Yalnızca özel dikim gömlek</small></span><b>+0 TL</b></label><label class="accessory-choice"><input type="radio" name="cufflink" value="oval" ${cufflink?'checked':''}><img src="assets/cufflinks.png" alt="Kutuda siyah oval kol düğmesi çifti" width="60" height="75"><span>Siyah Oval<small>Gümüş tonlu · bir çift · kutulu</small></span><b>+${money(cufflinkPrice)}</b></label><small>İsteğe bağlı ek ürün. Görsel ve fiyat örnektir.</small></fieldset>`:'';}
function details(){if(backendCheckout){const ids=['signature','french-cuff','blue-stripe'];location.href='checkout.html?'+new URLSearchParams({doctor:chosen.id,product:ids[product],cufflinks:hasCufflink()?'1':'0'});return;}show(`<div class="eyebrow">01 / HEDİYENİZİN İNCELİKLERİ</div><h2>Teşekkürünüzü kişiselleştirin.</h2>${summary()}<form id="giftform">${accessoryOptions()}<label for="sender">Adınız ve soyadınız</label><input id="sender" required maxlength="100" autocomplete="name" value="${esc(draft.sender||'')}"><label for="email">Teslimat bilgisi için e-posta adresiniz</label><input id="email" type="email" required maxlength="160" autocomplete="email" value="${esc(draft.email||'')}"><label for="note">Hediyenin içine eklenecek notunuz</label><textarea id="note" maxlength="400" placeholder="İlginiz ve emeğiniz için teşekkür ederim…">${esc(draft.note||'')}</textarea><p class="notice">Bu bir tasarım önizlemesidir. Bilgiler gönderilmez ve sayfa kapandığında silinir. Denemede örnek bilgiler kullanabilirsiniz.</p><div class="actions"><button type="button" class="secondary" id="cancel">Vazgeç</button><button class="primary">Hediyeyi gözden geçir →</button></div></form>`);document.querySelectorAll('input[name="cufflink"]').forEach(input=>input.onchange=()=>{cufflink=input.value==='oval';$('#orderPrice').innerHTML=priceSummary();});$('#cancel').onclick=()=>dialog.close();$('#giftform').onsubmit=e=>{e.preventDefault();draft={sender:$('#sender').value.trim(),email:$('#email').value.trim(),note:$('#note').value.trim()};if(!draft.sender)return;review();};}
function review(){show(`<div class="eyebrow">02 / SON BİR BAKIŞ</div><h2>İçten bir teşekkür, hazır.</h2>${summary()}<p><strong>Gönderen:</strong> ${esc(draft.sender)}</p><p><strong>Bildirim adresi:</strong> ${esc(draft.email)}</p><div class="summary">${esc(draft.note||'Not eklenmedi.')}</div><p>Gerçek siparişte doktorunuzla iletişim kurularak hediye kabulü, ölçü ve kumaş tercihleri alınacak; dikimden sonra seçtiği adrese gönderilecektir.</p><p class="notice">Ödeme altyapısı henüz bağlı değil. Aşağıdaki düğme yalnızca örnek takip ekranını açar; sipariş oluşturmaz ve ücret almaz.</p><div class="actions"><button class="secondary" id="back">← Düzenle</button><button class="primary" id="demo">Deneme akışını tamamla →</button></div>`);$('#back').onclick=details;$('#demo').onclick=()=>{lastOrder={doctor:chosen.name,gift:products[product][0],accessory:hasCufflink()?'Siyah Oval kol düğmesi (çift)':'',total:total()};tracking(true);};}
function tracking(done=false){show(`<div class="eyebrow">HEDİYE TAKİBİ / ÖRNEK GÖRÜNÜM</div><h2>${done?'Teşekkürünüzün yolculuğu.':'Hediyeniz hangi aşamada?'}</h2><p class="notice">Bu örnek takip ekranıdır. Gerçek sipariş, doktor araması veya teslimat bildirimi oluşturulmadı.</p>${lastOrder?`<div class="summary"><strong>${esc(lastOrder.doctor)}</strong><p>${esc(lastOrder.gift)}</p>${lastOrder.accessory?`<p>${esc(lastOrder.accessory)}</p>`:''}<p>Örnek toplam: ${money(lastOrder.total)}</p></div>`:''}<ol class="timeline"><li>01 · Sipariş alındı — örnek aşama</li><li>02 · Doktorun hediye kabulü bekleniyor</li><li>03 · Ölçüler ve kumaş tercihi alınıyor</li><li>04 · Özel dikim hazırlanıyor</li><li>05 · Notunuzla birlikte kargoya veriliyor</li><li>06 · Teslim edildi — size bilgi veriliyor</li></ol><p>Gerçek takip ve bildirimler, seçilecek mağaza altyapısına bağlanacaktır.</p>`);}
$('#track').onclick=()=>tracking();
fetch('doctors.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{doctors=d;}).catch(()=>{$('#selected').textContent='Doktor listesi şu anda yüklenemiyor. Lütfen sayfayı yenileyin.';});


let backendCheckout=false;
fetch('/api/storefront').then(r=>r.ok?r.json():null).then(c=>{backendCheckout=Boolean(c&&c.checkout);if(backendCheckout){$('#track').onclick=()=>{location.href='checkout.html?return=1';};}}).catch(()=>{});
