'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let doctors=[],chosen=null,product=0,draft={},lastOrder=null,cufflink=false;
const products=[['İmza Gömlek','3.500 TL'],['Manşet Koleksiyonu','4.500 TL'],['Çizgili İmza','3.750 TL']];
const prices=[3500,4500,3750],cufflinkPrice=1250;
const money=n=>n.toLocaleString('tr-TR')+' TL';
const hasCufflink=()=>product===1&&cufflink;
const total=()=>prices[product]+(hasCufflink()?cufflinkPrice:0);
const norm=s=>s.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');
const dialog=$('#flow');
function show(html){$('#flowbody').innerHTML=html;if(!dialog.open)dialog.showModal();}
$('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function find(){let q=norm($('#doctor').value.trim());let matches=doctors.filter(d=>norm(d.name+' '+d.branch+' '+d.institution).includes(q)).slice(0,12);$('#results').hidden=false;$('#doctor').setAttribute('aria-expanded','true');$('#results').innerHTML=matches.length?matches.map(d=>`<button data-doctor="${d.id}">${esc(d.title+' '+d.name)}<span>${esc(d.branch)}</span><span>${esc(d.institution)}</span></button>`).join(''):'<p>Bu isim listede bulunamadı. Doktor adını veya branşını farklı yazarak deneyin.</p>';$('#results').querySelectorAll('button').forEach(b=>b.onclick=()=>selectDoctor(b.dataset.doctor));}
function selectDoctor(id){chosen=doctors.find(d=>d.id===id);if(!chosen)throw Error('Doktor bulunamadı');$('#doctor').value=chosen.name;$('#selected').textContent=chosen.name+' seçildi. Şimdi hediyenizi seçebilirsiniz.';$('#results').hidden=true;$('#doctor').setAttribute('aria-expanded','false');$('#koleksiyon').scrollIntoView({behavior:'smooth'});}
$('#doctor').addEventListener('input',()=>{chosen=null;$('#selected').textContent='';find();});$('#doctor').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();find();$('#results button')?.focus();}if(e.key==='Escape'){$('#results').hidden=true;$('#doctor').setAttribute('aria-expanded','false');}});$('#search').onclick=find;
document.addEventListener('click',e=>{if(!e.target.closest('.finder')){$('#results').hidden=true;$('#doctor').setAttribute('aria-expanded','false');}});
document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{product=Number(b.dataset.product);if(product!==1)cufflink=false;if(!chosen){$('#doctor').focus();$('#doctor').scrollIntoView({block:'center',behavior:'smooth'});find();$('#selected').textContent='Önce hediyeyi göndereceğiniz doktoru seçin.';return;}details();});
function summary(){return `<div class="summary"><strong>${esc(products[product][0])} · ${products[product][1]}</strong><p>${esc(chosen.title+' '+chosen.name)}</p><p>${esc(chosen.branch)} · ${esc(chosen.institution)}</p><div id="orderPrice" aria-live="polite">${priceSummary()}</div></div>`;}
function priceSummary(){return `${product===1?`<p>${hasCufflink()?'Siyah Oval kol düğmesi (çift) · +'+money(cufflinkPrice):'Kol düğmesi eklenmedi'}</p>`:''}<p class="order-total"><span>Örnek toplam</span><strong>${money(total())}</strong></p>`;}
function accessoryOptions(){return product===1?`<fieldset class="cufflink-options"><legend>Manşetin son dokunuşu</legend><p>Çift manşet kol düğmesiyle kullanılır. Doktorunuzun kendi kol düğmesi varsa eklemeden devam edebilirsiniz.</p><label class="accessory-choice"><input type="radio" name="cufflink" value="none" ${!cufflink?'checked':''}><span>Kol düğmesi ekleme<small>Yalnızca özel dikim gömlek</small></span><b>+0 TL</b></label><label class="accessory-choice"><input type="radio" name="cufflink" value="oval" ${cufflink?'checked':''}><img src="assets/cufflinks.png" alt="Kutuda siyah oval kol düğmesi çifti" width="60" height="75"><span>Siyah Oval<small>Gümüş tonlu · bir çift · kutulu</small></span><b>+${money(cufflinkPrice)}</b></label><small>İsteğe bağlı ek ürün. Görsel ve fiyat örnektir.</small></fieldset>`:'';}
function details(){show(`<div class="eyebrow">01 / HEDİYENİZİN İNCELİKLERİ</div><h2>Teşekkürünüzü kişiselleştirin.</h2>${summary()}<form id="giftform">${accessoryOptions()}<label for="sender">Adınız ve soyadınız</label><input id="sender" required maxlength="100" autocomplete="name" value="${esc(draft.sender||'')}"><label for="email">Teslimat bilgisi için e-posta adresiniz</label><input id="email" type="email" required maxlength="160" autocomplete="email" value="${esc(draft.email||'')}"><label for="note">Hediyenin içine eklenecek notunuz</label><textarea id="note" maxlength="400" placeholder="İlginiz ve emeğiniz için teşekkür ederim…">${esc(draft.note||'')}</textarea><p class="notice">Bu bir tasarım önizlemesidir. Bilgiler gönderilmez ve sayfa kapandığında silinir. Denemede örnek bilgiler kullanabilirsiniz.</p><div class="actions"><button type="button" class="secondary" id="cancel">Vazgeç</button><button class="primary">Hediyeyi gözden geçir →</button></div></form>`);document.querySelectorAll('input[name="cufflink"]').forEach(input=>input.onchange=()=>{cufflink=input.value==='oval';$('#orderPrice').innerHTML=priceSummary();});$('#cancel').onclick=()=>dialog.close();$('#giftform').onsubmit=e=>{e.preventDefault();draft={sender:$('#sender').value.trim(),email:$('#email').value.trim(),note:$('#note').value.trim()};if(!draft.sender)return;review();};}
function review(){show(`<div class="eyebrow">02 / SON BİR BAKIŞ</div><h2>İçten bir teşekkür, hazır.</h2>${summary()}<p><strong>Gönderen:</strong> ${esc(draft.sender)}</p><p><strong>Bildirim adresi:</strong> ${esc(draft.email)}</p><div class="summary">${esc(draft.note||'Not eklenmedi.')}</div><p>Gerçek siparişte doktorunuzla iletişim kurularak hediye kabulü, ölçü ve kumaş tercihleri alınacak; dikimden sonra seçtiği adrese gönderilecektir.</p><p class="notice">Ödeme altyapısı henüz bağlı değil. Aşağıdaki düğme yalnızca örnek takip ekranını açar; sipariş oluşturmaz ve ücret almaz.</p><div class="actions"><button class="secondary" id="back">← Düzenle</button><button class="primary" id="demo">Deneme akışını tamamla →</button></div>`);$('#back').onclick=details;$('#demo').onclick=()=>{lastOrder={doctor:chosen.name,gift:products[product][0],accessory:hasCufflink()?'Siyah Oval kol düğmesi (çift)':'',total:total()};tracking(true);};}
function tracking(done=false){show(`<div class="eyebrow">HEDİYE TAKİBİ / ÖRNEK GÖRÜNÜM</div><h2>${done?'Teşekkürünüzün yolculuğu.':'Hediyeniz hangi aşamada?'}</h2><p class="notice">Bu örnek takip ekranıdır. Gerçek sipariş, doktor araması veya teslimat bildirimi oluşturulmadı.</p>${lastOrder?`<div class="summary"><strong>${esc(lastOrder.doctor)}</strong><p>${esc(lastOrder.gift)}</p>${lastOrder.accessory?`<p>${esc(lastOrder.accessory)}</p>`:''}<p>Örnek toplam: ${money(lastOrder.total)}</p></div>`:''}<ol class="timeline"><li>01 · Sipariş alındı — örnek aşama</li><li>02 · Doktorun hediye kabulü bekleniyor</li><li>03 · Ölçüler ve kumaş tercihi alınıyor</li><li>04 · Özel dikim hazırlanıyor</li><li>05 · Notunuzla birlikte kargoya veriliyor</li><li>06 · Teslim edildi — size bilgi veriliyor</li></ol><p>Gerçek takip ve bildirimler, seçilecek mağaza altyapısına bağlanacaktır.</p>`);}
$('#track').onclick=()=>tracking();
fetch('doctors.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{doctors=d;}).catch(()=>{$('#selected').textContent='Doktor listesi şu anda yüklenemiyor. Lütfen sayfayı yenileyin.';});

