'use strict';
let key='',orders=[],generation=0;const $=id=>document.getElementById(id);
const stages={awaiting_payment:'Ödeme bekleniyor',payment_failed:'Ödeme başarısız',awaiting_acceptance:'Hediye kabulü bekleniyor',measurements:'Onaylandı · Ölçüler alınıyor',tailoring:'Hazırlanıyor',shipped:'Kargoda',delivered:'Teslim edildi',refund_requested:'İade talebi'};
const transitions={awaiting_acceptance:['measurements','refund_requested'],measurements:['tailoring','refund_requested'],tailoring:['shipped','refund_requested'],shipped:['delivered']};
const payments={pending:'Ödeme bekleniyor',paid:'Ödeme doğrulandı',failed:'Ödeme başarısız'};
const money=n=>(n/100).toLocaleString('tr-TR',{style:'currency',currency:'TRY'});
function text(tag,value,cls){const node=document.createElement(tag);node.textContent=value;if(cls)node.className=cls;return node;}
function logout(){generation++;key='';orders=[];$('key').value='';$('orders').replaceChildren();$('dashboard').hidden=true;$('loginPanel').hidden=false;$('message').textContent='Çıkış yapıldı.';}
async function request(path,options={}){const res=await fetch(path,{...options,headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'}});const data=await res.json();if(!res.ok){if(res.status===401)logout();throw Error(data.error||'İşlem tamamlanamadı.');}return data;}
function renderOrders(){
 const q=$('search').value.toLocaleLowerCase('tr').trim(),pf=$('paymentFilter').value,df=$('deliveryFilter').value;
 const list=orders.filter(o=>(o.id+' '+o.buyer.name+' '+o.doctor.name).toLocaleLowerCase('tr').includes(q)&&(df==='all'||(o.delivery_method||'doctor')===df)&&(pf==='all'||(pf==='live'?o.mode==='live':pf==='test'?o.mode!=='live':o.payment===pf)));
 $('countAll').textContent=list.length;$('countPaid').textContent=list.filter(o=>o.payment==='paid').length;$('countActive').textContent=list.filter(o=>o.payment==='paid'&&['awaiting_acceptance','measurements','tailoring'].includes(o.stage)).length;$('paidAmount').textContent=money(list.filter(o=>o.payment==='paid').reduce((s,o)=>s+o.amount,0));
 $('orders').replaceChildren();if(!list.length){$('orders').append(text('p','Bu filtrelerle eşleşen sipariş bulunamadı.','empty'));return;}
 for(const o of list){
 const card=text('article','','admin-order'),head=text('div','','order-heading'),title=text('div','');title.append(text('h2',o.doctor.title+' '+o.doctor.name),text('p',o.id+' · '+new Date(o.created*1000).toLocaleString('tr-TR'),'order-id'));head.append(title,text('strong',money(o.amount),'admin-total'));card.append(head);
 const badges=text('div','','badges');badges.append(text('span',payments[o.payment]||o.payment,'badge '+(o.payment==='paid'?'paid':'')),text('span',stages[o.stage]||o.stage,'badge'),text('span',o.mode==='live'?'CANLI':o.mode==='test'?'PAYTR TESTİ — GERÇEK TAHSİLAT DEĞİL':'DENEME — ÖDEME KAPALI','badge'));card.append(badges);card.append(orderProgress(o));
 const cols=text('div','','order-columns'),buyer=text('div',''),gift=text('div',''),delivery=text('div','','delivery-box');buyer.append(text('h3','Gönderen'),text('p',o.buyer.name),text('p',o.buyer.email),text('p',o.buyer.phone));gift.append(text('h3','Hediye & kişisel not'),text('p',o.items.map(i=>i.name+' · '+money(i.price)).join('\n')),text('p',o.note||'Not eklenmedi.'));
 const toBuyer=o.delivery_method==='buyer';delivery.append(text('h3',toBuyer?'Gönderene teslim':'Doğrudan doktora teslim'),text('p',toBuyer?'Gönderen, hediyeyi doktoruna kendisi sunacak.':'Teslimat adresini doktorla ayrıca doğrulayın.'),text('p',(toBuyer?'Paketin gönderileceği adres: ':'Gönderenin adresi (doktorun teslimat adresi değildir): ')+o.buyer.address),text('p','Kurum: '+o.doctor.institution));if(o.tracking)delivery.append(text('p','Kargo: '+o.tracking));cols.append(buyer,gift,delivery);card.append(cols);
 if(o.payment==='paid'&&transitions[o.stage]){
 const form=document.createElement('form');form.className='order-controls';const stageLabel=document.createElement('fieldset');stageLabel.className='stage-choices';stageLabel.append(text('legend','Siparişin sonraki adımını seçin'));const select={value:transitions[o.stage][0]};for(const s of transitions[o.stage]){const choice=text('label','','stage-choice'),radio=document.createElement('input');radio.type='radio';radio.name='stage-'+o.id;radio.value=s;radio.checked=s===select.value;radio.onchange=()=>{select.value=s;updateRequirement();};choice.append(radio,text('span',stages[s]));stageLabel.append(choice);}
 const trackLabel=text('label','Kargo firması ve takip numarası'),tracking=document.createElement('input');tracking.value=o.tracking;tracking.maxLength=160;tracking.placeholder='Örn. Kargo firması · Takip no';trackLabel.append(tracking);const save=text('button','Aşamayı kaydet','primary');const notice=text('p','Aşama değişikliği e-posta/SMS göndermez. İade talebi, PayTR üzerinden para iadesi yapmaz.');
 function updateRequirement(){tracking.required=select.value==='shipped';trackLabel.hidden=!['shipped','delivered'].includes(select.value);}updateRequirement();
 form.onsubmit=async e=>{e.preventDefault();const session=generation;save.disabled=true;try{await request('/api/admin/orders/'+o.id,{method:'PATCH',body:JSON.stringify({stage:select.value,version:o.version,tracking:tracking.value})});if(session!==generation)return;await load();$('message').textContent='Sipariş aşaması güncellendi.';}catch(e){if(session===generation)$('message').textContent=e.message;}finally{save.disabled=false;}};
 form.append(stageLabel,trackLabel,save,notice);card.append(form);
 }else if(o.payment!=='paid'){card.append(text('p','Ödeme doğrulanmadan üretim ve kargo aşamalarına geçilemez.','session-note'));}
 $('orders').append(card);
 }
}
async function load(){const session=generation;const data=await request('/api/admin/orders');if(session!==generation||!key)return;orders=data.orders;const m=data.mail;$('mailStatus').textContent=!m?.configured?'Sipariş e-postaları: bağlantı henüz etkin değil.':`Sipariş e-postaları: etkin · Servise iletilen ${m.sent} · Kuyrukta ${m.pending} · Kontrol gereken ${m.review}${m.test_enabled?' · Test bildirimleri açık':''}. Servise iletim, gelen kutusuna teslim garantisi değildir.`;$('loginPanel').hidden=true;$('dashboard').hidden=false;renderOrders();$('message').textContent='Liste güncellendi · '+new Date().toLocaleTimeString('tr-TR');try{const r=await fetch('/api/storefront');const c=await r.json();if(session!==generation)return;$('storeMode').textContent=c.payment_mode==='live'?'Mağaza: canlı ödeme açık.':c.payment_mode==='test'?'Mağaza: PayTR test ortamı. Gerçek tahsilat yapılmaz.':'Mağaza: gerçek ödeme kapalı. Kayıtlar deneme siparişidir.';}catch{if(session===generation)$('storeMode').textContent='Mağazanın ödeme durumu okunamadı.';}}
$('login').onsubmit=async e=>{e.preventDefault();generation++;key=$('key').value.trim();$('key').value='';$('loginButton').disabled=true;try{await load();}catch(e){key='';$('message').textContent=e.message;}finally{$('loginButton').disabled=false;}};
$('reload').onclick=async()=>{$('reload').disabled=true;try{await load();}catch(e){$('message').textContent=e.message;}finally{$('reload').disabled=false;}};$('logout').onclick=logout;
$('search').oninput=renderOrders;$('paymentFilter').onchange=renderOrders;$('deliveryFilter').onchange=renderOrders;
